spring:
  profiles:
    active: default

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

application:
  security:
    jwt:
      secret-key: ${JWT_256SECRETKEY}
      expiration: 86400000 # 1 Day
      refresh-token:
        expiration: 604800000 # 7 Days
